service: ipsum-generator

provider:
  name: aws
  runtime: nodejs8.10

package:
  include: handler.ts

functions:
  generateIpsum:
    handler: handler.generateIpsum
    events:
      - http:
          path: generateIpsum
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
